### ISSUE TITLE
Consider enabling `react/jsx-wrap-multilines`

### ISSUE THREAD

**Issue by wallzero** [gajus/eslint-config-mores-react#2]
I am just curious if there is a reason [`react/jsx-wrap-multilines`](https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-wrap-multilines.md) has been disabled. Could it be renabled?

**Comment by gajus** [comment]
I must admit that this was a mistake. It will be re-enabled.

**Comment by gajus** [comment]
This issue should go to https://github.com/gajus/eslint-config-canonical.
